name: UCLA BMES Build Team
title: "UCLA BMES Build Team"

exclude:
  - README.md
  - .gitignore

author:
  name: Build Team Project Managers
  email: bmes.build.team@gmail.com

theme: jekyll-theme-primer

